---
- name: main | Install necessities
  apt:
    pkg:
     - vim
     - unattended-upgrades
     - screen
     - bash
     - open-vm-tools
     - tzdata
     - curl
     - software-properties-common
     - unzip
    update_cache: yes
    state: latest

#- name: Set timezone to America/Los_Angeles (common-ubuntu:ntp.yml)
#  timezone:
#    name: America/Los_Angeles

- import_tasks: python3.yml
- import_tasks: ansible.yml
- import_tasks: awscli.yml
