---
- name: reboot | Check if a reboot is required
  register: isreboot
  stat:
    path: /var/run/reboot-required
    get_md5: no


- name: reboot | Reboot if needed
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: isreboot.stat.exists
